name: Update ical

on:
  push:
    branches: main
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: mkdir -p gh-pages
      - name: Setup Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          args: "--exit-node=${{ secrets.TAILSCALE_EXIT_NODE }}"
          tags: tag:github-actions
      - name: Verify Tailscale
        run: |
          echo "Available exit nodes:"
          tailscale status | grep 'exit node'
          echo "IP from ifconfig.me:"
          curl -s https://ifconfig.me
      - run: npm run generate gh-pages/bfi.ics
      - run: npm install --no-save markdown-to-html-cli
      - run: npx markdown-to-html --no-corners --output gh-pages/index.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages
      - id: deployment
        uses: actions/deploy-pages@v4
